window.PORTFOLIO_DATA = {
  "meta": {
    "priceDate": "2026-06-30",
    "targetCapital": 235552.91,
    "currentPortfolioValue": 235552.9,
    "modelPortfolioValue": 234403.47,
    "residualValue": 1149.43,
    "cashCurrent": 26854.02,
    "liquidityCurrentValue": 34993.22,
    "cashTargetPct": 8.0,
    "cashMinimumPct": 5.0,
    "liquidityTargetPct": 15.0,
    "liquidityCurrentPct": 14.86,
    "residualCount": 4,
    "modelAssetCount": 26,
    "holdingsCount": 21,
    "watchlistCount": 34,
    "marketPriceCount": 53,
    "fxRateCount": 3,
    "notes": [
      "O modelo usa o fechamento mais recente do snapshot em 2026-06-30 e converte tudo para USD.",
      "Cash, XOVR e bond ECOPET formam a faixa de liquidez/defesa.",
      "Posicoes residuais fora do modelo aparecem separadas para nao mascarar risco."
    ],
    "baseTopFiveShare": 31.0,
    "nonUsdShare": 2.0
  },
  "scenarios": [
    {
      "id": "study",
      "label": "Base do estudo",
      "description": "Replica o plano principal e preserva o corredor de liquidez de 15%.",
      "cashTargetPct": 8.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 1.0,
        "defense_space": 1.0,
        "uranium": 1.0,
        "minerals": 1.0,
        "tail": 1.0
      }
    },
    {
      "id": "defensive",
      "label": "Defensivo global",
      "description": "Sobe caixa, corta a cauda e privilegia o nucleo de qualidade.",
      "cashTargetPct": 10.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 1.06,
        "defense_space": 0.95,
        "uranium": 0.9,
        "minerals": 0.85,
        "tail": 0.6
      }
    },
    {
      "id": "convex",
      "label": "Convexidade",
      "description": "Reduz caixa e amplifica optionalidade em energia, defesa e minerais.",
      "cashTargetPct": 6.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 0.94,
        "defense_space": 1.05,
        "uranium": 1.16,
        "minerals": 1.12,
        "tail": 1.35
      }
    }
  ],
  "themes": [
    {
      "id": "liquidity",
      "label": "Liquidez",
      "description": "Cash, XOVR e o bond ECOPET preservam a faixa de defesa do modelo.",
      "accent": "#d08b2e",
      "assets": [
        "Cash",
        "XOVR",
        "ECOPET_BOND"
      ],
      "assetCount": 3
    },
    {
      "id": "quality",
      "label": "Nucleo qualidade",
      "description": "MSFT, NVDA, AMZN, GOOGL, JPM e IBM financiam a carteira e reduzem ruído.",
      "accent": "#4aa3df",
      "assets": [
        "AMZN",
        "GOOGL",
        "MSFT",
        "NVDA",
        "IBM",
        "JPM"
      ],
      "assetCount": 6
    },
    {
      "id": "defense_space",
      "label": "Defesa e espaco",
      "description": "RKLB, ASTS, KTOS, SHLD e RTX capturam a tese geopolitica e orbital.",
      "accent": "#7e8cff",
      "assets": [
        "RTX",
        "KTOS",
        "SHLD",
        "RKLB",
        "ASTS"
      ],
      "assetCount": 5
    },
    {
      "id": "uranium",
      "label": "Uranio e nuclear",
      "description": "URA, NXE, SMR, UUUU e NAUFF refletem o ciclo de energia estrategica.",
      "accent": "#c86df0",
      "assets": [
        "URA",
        "NXE",
        "SMR",
        "UUUU",
        "NAUFF"
      ],
      "assetCount": 5
    },
    {
      "id": "minerals",
      "label": "Minerais criticos",
      "description": "COPX, ARR, MP e SGML conectam cobre, terras raras e lito ao superciclo.",
      "accent": "#2bc6a4",
      "assets": [
        "COPX",
        "ARR.AX",
        "MP",
        "SGML"
      ],
      "assetCount": 4
    },
    {
      "id": "tail",
      "label": "Cauda especulativa",
      "description": "QBTS, RGTI, LAES, HYMC e USGDF ficam como opcionalidade de cauda.",
      "accent": "#ff7a59",
      "assets": [
        "QBTS",
        "RGTI",
        "LAES",
        "HYMC",
        "USGDF"
      ],
      "assetCount": 5
    }
  ],
  "study": {
    "principles": [
      "Construa um basket, nao uma aposta unica.",
      "Aceite que varias teses falhem; poucos vencedores pagam a conta.",
      "Use ativos estrategicos com potencial de rerating estrutural.",
      "Preserve liquidez e respeite o piso de 5% em caixa.",
      "Dimensone optionalidade por tema, geografia e horizonte."
    ],
    "basketBlueprint": [
      {
        "label": "Rare earths",
        "weight": 20,
        "examples": [
          "ARR",
          "Ucore",
          "Aclara",
          "Energy Fuels"
        ]
      },
      {
        "label": "Uranium",
        "weight": 20,
        "examples": [
          "NXE",
          "DNN",
          "FCU",
          "DYL"
        ]
      },
      {
        "label": "Defense / space",
        "weight": 20,
        "examples": [
          "ASTS",
          "RKLB",
          "KTOS",
          "RCAT"
        ]
      },
      {
        "label": "AI biotech",
        "weight": 15,
        "examples": [
          "RXRX",
          "BEAM",
          "CRSP"
        ]
      },
      {
        "label": "Copper / lithium",
        "weight": 15,
        "examples": [
          "IVN",
          "SGML",
          "PMET",
          "LAAC"
        ]
      },
      {
        "label": "Nuclear",
        "weight": 10,
        "examples": [
          "SMR",
          "OKLO"
        ]
      }
    ],
    "topIdeas": [
      {
        "symbol": "ARR",
        "name": "American Rare Earths",
        "themeLabel": "Minerais criticos",
        "studyBucket": "rare_earths",
        "priority": "alta",
        "currency": "AUD",
        "currentPrice": 0.38,
        "currentPriceUsd": 0.26,
        "targetPrice": 0.54,
        "targetPriceUsd": 0.37,
        "upsidePct": 45.0,
        "thesis": "top 5; terras raras EUA, geopolítica, muito risco"
      },
      {
        "symbol": "ASTS",
        "name": "AST SpaceMobile",
        "themeLabel": "Defesa e espaco",
        "studyBucket": "defense_space",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 86.1,
        "currentPriceUsd": 86.1,
        "targetPrice": 120.54,
        "targetPriceUsd": 120.54,
        "upsidePct": 40.0,
        "thesis": "top 5; infraestrutura celular via satélite"
      },
      {
        "symbol": "NXE",
        "name": "NexGen Energy",
        "themeLabel": "Uranio e nuclear",
        "studyBucket": "uranium",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 9.45,
        "currentPriceUsd": 9.45,
        "targetPrice": 12.28,
        "targetPriceUsd": 12.28,
        "upsidePct": 30.0,
        "thesis": "top 5; ativo tier-1 em urânio"
      },
      {
        "symbol": "RKLB",
        "name": "Rocket Lab",
        "themeLabel": "Cauda especulativa",
        "studyBucket": "Espaço/defesa",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 100.07,
        "currentPriceUsd": 100.07,
        "targetPrice": 135.09,
        "targetPriceUsd": 135.09,
        "upsidePct": 35.0,
        "thesis": "top 5; execução operacional"
      },
      {
        "symbol": "SMR",
        "name": "NuScale Power",
        "themeLabel": "Cauda especulativa",
        "studyBucket": "Nuclear SMR",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 10.15,
        "currentPriceUsd": 10.15,
        "targetPrice": 13.19,
        "targetPriceUsd": 13.19,
        "upsidePct": 30.0,
        "thesis": "top 5; opcionalidade em SMRs"
      }
    ]
  },
  "marketPrices": [
    {
      "symbol": "ALL.L",
      "yahoo": "ALL.L",
      "currency": "GBP",
      "currencyRaw": "GBp",
      "closeLocal": 0.16,
      "closeUsd": 0.21,
      "fxToUsd": 1.327986,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ALL.L?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "AMZN",
      "yahoo": "AMZN",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 241.7,
      "closeUsd": 241.7,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/AMZN?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "ARA.TO",
      "yahoo": "ARA.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 4.12,
      "closeUsd": 2.9,
      "fxToUsd": 0.703354,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ARA.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "ARR.AX",
      "yahoo": "ARR.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 0.38,
      "closeUsd": 0.26,
      "fxToUsd": 0.689465,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ARR.AX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "ASCU.TO",
      "yahoo": "ASCU.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 8.06,
      "closeUsd": 5.67,
      "fxToUsd": 0.703354,
      "date": "2026-06-29",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ASCU.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "ASTS",
      "yahoo": "ASTS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 86.1,
      "closeUsd": 86.1,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ASTS?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "BEAM",
      "yahoo": "BEAM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 33.48,
      "closeUsd": 33.48,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/BEAM?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "BKSY",
      "yahoo": "BKSY",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 28.74,
      "closeUsd": 28.74,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/BKSY?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "CDZI",
      "yahoo": "CDZI",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 4.08,
      "closeUsd": 4.08,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/CDZI?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "COPX",
      "yahoo": "COPX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 75.29,
      "closeUsd": 75.29,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/COPX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "CRSP",
      "yahoo": "CRSP",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 55.62,
      "closeUsd": 55.62,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/CRSP?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "DNN",
      "yahoo": "DNN",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.08,
      "closeUsd": 3.08,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/DNN?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "DYL.AX",
      "yahoo": "DYL.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 1.45,
      "closeUsd": 1.0,
      "fxToUsd": 0.689465,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/DYL.AX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "FCU.TO",
      "yahoo": "FCU.TO",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/FCU.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "GLO.TO",
      "yahoo": "GLO.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 0.62,
      "closeUsd": 0.44,
      "fxToUsd": 0.703354,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/GLO.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "GOOGL",
      "yahoo": "GOOGL",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 361.21,
      "closeUsd": 361.21,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/GOOGL?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "HYMC",
      "yahoo": "HYMC",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 23.07,
      "closeUsd": 23.07,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/HYMC?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "IBM",
      "yahoo": "IBM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 286.25,
      "closeUsd": 286.25,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/IBM?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "ICG.CN",
      "yahoo": "ICG.CN",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 0.44,
      "closeUsd": 0.31,
      "fxToUsd": 0.703354,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ICG.CN?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "IVN.TO",
      "yahoo": "IVN.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 11.11,
      "closeUsd": 7.81,
      "fxToUsd": 0.703354,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/IVN.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "JPM",
      "yahoo": "JPM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 334.07,
      "closeUsd": 334.07,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/JPM?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "KTOS",
      "yahoo": "KTOS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 53.04,
      "closeUsd": 53.04,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/KTOS?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "LAAC",
      "yahoo": "LAAC",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LAAC?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "LAES",
      "yahoo": "LAES",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.1,
      "closeUsd": 3.1,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LAES?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "LYC.AX",
      "yahoo": "LYC.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 18.09,
      "closeUsd": 12.47,
      "fxToUsd": 0.689465,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LYC.AX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "MOS",
      "yahoo": "MOS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 21.3,
      "closeUsd": 21.3,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MOS?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "MP",
      "yahoo": "MP",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 54.28,
      "closeUsd": 54.28,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MP?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "MSFT",
      "yahoo": "MSFT",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 384.28,
      "closeUsd": 384.28,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MSFT?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NAUFF",
      "yahoo": "NAUFF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 1.49,
      "closeUsd": 1.49,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NAUFF?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NGEX.V",
      "yahoo": "NGEX.V",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NGEX.V?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NTDOY",
      "yahoo": "NTDOY",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 10.75,
      "closeUsd": 10.75,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NTDOY?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NTR",
      "yahoo": "NTR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 63.57,
      "closeUsd": 63.57,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NTR?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NVDA",
      "yahoo": "NVDA",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 197.58,
      "closeUsd": 197.58,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NVDA?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "NXE",
      "yahoo": "NXE",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 9.45,
      "closeUsd": 9.45,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NXE?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "OKLO",
      "yahoo": "OKLO",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 52.45,
      "closeUsd": 52.45,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/OKLO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "PL",
      "yahoo": "PL",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 31.61,
      "closeUsd": 31.61,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PL?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "PLTR",
      "yahoo": "PLTR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 125.73,
      "closeUsd": 125.73,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PLTR?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "PMET.V",
      "yahoo": "PMET.V",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PMET.V?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "QBTS",
      "yahoo": "QBTS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 23.5,
      "closeUsd": 23.5,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/QBTS?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "RCAT",
      "yahoo": "RCAT",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 10.55,
      "closeUsd": 10.55,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RCAT?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "RGTI",
      "yahoo": "RGTI",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 18.68,
      "closeUsd": 18.68,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RGTI?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "RKLB",
      "yahoo": "RKLB",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 100.07,
      "closeUsd": 100.07,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RKLB?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "RTX",
      "yahoo": "RTX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 191.78,
      "closeUsd": 191.78,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RTX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "RXRX",
      "yahoo": "RXRX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.67,
      "closeUsd": 3.67,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RXRX?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "SGML",
      "yahoo": "SGML",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 12.41,
      "closeUsd": 12.41,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SGML?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "SHLD",
      "yahoo": "SHLD",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 61.2,
      "closeUsd": 61.2,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SHLD?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "SLS.TO",
      "yahoo": "SLS.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 11.93,
      "closeUsd": 8.39,
      "fxToUsd": 0.703354,
      "date": "2026-06-30",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SLS.TO?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "SMR",
      "yahoo": "SMR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 10.15,
      "closeUsd": 10.15,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SMR?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "URA",
      "yahoo": "URA",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 43.18,
      "closeUsd": 43.18,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/URA?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "USGDF",
      "yahoo": "USGDF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 0.11,
      "closeUsd": 0.11,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/USGDF?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "UURAF",
      "yahoo": "UURAF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.39,
      "closeUsd": 3.39,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/UURAF?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "UUUU",
      "yahoo": "UUUU",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 14.22,
      "closeUsd": 14.22,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/UUUU?period1=1781654400&period2=1783123200&interval=1d&events=history"
    },
    {
      "symbol": "XOVR",
      "yahoo": "XOVR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 21.11,
      "closeUsd": 21.11,
      "fxToUsd": 1.0,
      "date": "2026-07-01",
      "error": "",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/XOVR?period1=1781654400&period2=1783123200&interval=1d&events=history"
    }
  ],
  "fxRates": [
    {
      "currency": "AUD",
      "rate": 0.6912999749183655,
      "pair": "AUDUSD=X",
      "date": "2026-06-30",
      "error": "",
      "multiplier": 1.0
    },
    {
      "currency": "CAD",
      "rate": 0.7039774656295776,
      "pair": "CADUSD=X",
      "date": "2026-06-30",
      "error": "",
      "multiplier": 1.0
    },
    {
      "currency": "GBP",
      "rate": 1.325065016746521,
      "pair": "GBPUSD=X",
      "date": "2026-06-30",
      "error": "",
      "multiplier": 0.01
    },
    {
      "currency": "USD",
      "rate": 1.0,
      "pair": "USD",
      "date": "2026-06-30",
      "error": "",
      "multiplier": 1.0
    }
  ],
  "moves": [
    {
      "asset": "Cash",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 8.0,
      "baseTargetValue": 18844.23,
      "currentValue": 26854.02,
      "currentValueLocal": 0.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "baseTradeValue": -8009.79,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Preservar liquidez estrategica e cumprir o piso de 5% com folga.",
      "fixed": true,
      "priceDate": "",
      "priceError": ""
    },
    {
      "asset": "XOVR",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 2111.0,
      "currentValueLocal": 2111.0,
      "currentPrice": 21.11,
      "currentPriceUsd": 21.11,
      "baseTradeValue": 7311.12,
      "targetPrice": 21.95,
      "targetPriceUsd": 21.95,
      "upsidePct": 4.0,
      "bias": "manter como caixa equivalente",
      "thesis": "Aumentar equivalente defensivo para reduzir volatilidade sem sair de caixa.",
      "fixed": true,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "ECOPET_BOND",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "Colombia",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7066.59,
      "currentValue": 6028.2,
      "currentValueLocal": 0.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "baseTradeValue": 1038.39,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Manter renda fixa em USD como camada defensiva do modelo.",
      "fixed": true,
      "priceDate": "",
      "priceError": ""
    },
    {
      "asset": "AMZN",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "AMZN",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 11777.64,
      "currentValue": 12085.0,
      "currentValueLocal": 12085.0,
      "currentPrice": 241.7,
      "currentPriceUsd": 241.7,
      "baseTradeValue": -307.36,
      "targetPrice": 275.54,
      "targetPriceUsd": 275.54,
      "upsidePct": 14.0,
      "bias": "manter/aumentar moderado",
      "thesis": "Manter qualidade em cloud, ads e consumo, apenas aparando excesso pequeno.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "GOOGL",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "GOOGL",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 11777.64,
      "currentValue": 9030.25,
      "currentValueLocal": 9030.25,
      "currentPrice": 361.21,
      "currentPriceUsd": 361.21,
      "baseTradeValue": 2747.4,
      "targetPrice": 404.56,
      "targetPriceUsd": 404.56,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Aumentar para peso de nucleo pela combinacao de IA, search e cloud.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "MSFT",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "MSFT",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 14133.17,
      "currentValue": 19214.0,
      "currentValueLocal": 19214.0,
      "currentPrice": 384.28,
      "currentPriceUsd": 384.28,
      "baseTradeValue": -5080.83,
      "targetPrice": 422.71,
      "targetPriceUsd": 422.71,
      "upsidePct": 10.0,
      "bias": "manter",
      "thesis": "Preservar posicao core em cloud/IA, mas reduzir concentracao para financiar convexidade.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "NVDA",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "NVDA",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 8.0,
      "baseTargetValue": 18844.23,
      "currentValue": 39516.0,
      "currentValueLocal": 39516.0,
      "currentPrice": 197.58,
      "currentPriceUsd": 197.58,
      "baseTradeValue": -20671.77,
      "targetPrice": 217.34,
      "targetPriceUsd": 217.34,
      "upsidePct": 10.0,
      "bias": "reduzir peso",
      "thesis": "Continuar exposto a lideranca em IA, porem com disciplina de tamanho.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "IBM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "IBM",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 28625.0,
      "currentValueLocal": 28625.0,
      "currentPrice": 286.25,
      "currentPriceUsd": 286.25,
      "baseTradeValue": -19202.88,
      "targetPrice": 297.7,
      "targetPriceUsd": 297.7,
      "upsidePct": 4.0,
      "bias": "reduzir",
      "thesis": "Reduzir ativo defensivo de menor convexidade para liberar capital para teses do estudo.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "JPM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "JPM",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 14133.17,
      "currentValue": 33407.0,
      "currentValueLocal": 33407.0,
      "currentPrice": 334.07,
      "currentPriceUsd": 334.07,
      "baseTradeValue": -19273.83,
      "targetPrice": 354.11,
      "targetPriceUsd": 354.11,
      "upsidePct": 6.0,
      "bias": "reduzir",
      "thesis": "Manter banco de qualidade, mas reduzir peso elevado e dependencia de financeiro tradicional.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "RTX",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "RTX",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7066.59,
      "currentValue": 5753.4,
      "currentValueLocal": 5753.4,
      "currentPrice": 191.78,
      "currentPriceUsd": 191.78,
      "baseTradeValue": 1313.19,
      "targetPrice": 207.12,
      "targetPriceUsd": 207.12,
      "upsidePct": 8.0,
      "bias": "manter",
      "thesis": "Reforcar defesa core, com menor upside que RKLB e KTOS, mas melhor perfil defensivo.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "KTOS",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 3182.4,
      "currentValueLocal": 3182.4,
      "currentPrice": 53.04,
      "currentPriceUsd": 53.04,
      "baseTradeValue": 6239.72,
      "targetPrice": 62.59,
      "targetPriceUsd": 62.59,
      "upsidePct": 18.0,
      "bias": "manter",
      "thesis": "Aumentar exposicao a drones, sistemas autonomos e guerra eletronica.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "SHLD",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "SHLD",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 9180.0,
      "currentValueLocal": 9180.0,
      "currentPrice": 61.2,
      "currentPriceUsd": 61.2,
      "baseTradeValue": 242.12,
      "targetPrice": 68.54,
      "targetPriceUsd": 68.54,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Manter ETF de defesa como exposicao diversificada ao tema geopolitico.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "URA",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "URA",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 11777.64,
      "currentValue": 4318.0,
      "currentValueLocal": 4318.0,
      "currentPrice": 43.18,
      "currentPriceUsd": 43.18,
      "baseTradeValue": 7459.64,
      "targetPrice": 49.66,
      "targetPriceUsd": 49.66,
      "upsidePct": 15.0,
      "bias": "manter",
      "thesis": "Aumentar bloco de uranio pelo ciclo nuclear e pela demanda de energia para IA.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "COPX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "COPX",
      "role": "Opcionalidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 7529.0,
      "currentValueLocal": 7529.000000000001,
      "currentPrice": 75.29,
      "currentPriceUsd": 75.29,
      "baseTradeValue": 1893.12,
      "targetPrice": 84.32,
      "targetPriceUsd": 84.32,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Reforcar cobre como tese de eletrificacao global com risco mais diversificado.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "RKLB",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "RKLB",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 14133.17,
      "currentValue": 6004.2,
      "currentValueLocal": 6004.2,
      "currentPrice": 100.07,
      "currentPriceUsd": 100.07,
      "baseTradeValue": 8128.97,
      "targetPrice": 135.09,
      "targetPriceUsd": 135.09,
      "upsidePct": 35.0,
      "bias": "aumentar",
      "thesis": "Aumentar uma das top 5 do estudo, com execucao operacional real em espaco e defesa.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "ASTS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "ASTS",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 86.1,
      "currentPriceUsd": 86.1,
      "baseTradeValue": 9422.12,
      "targetPrice": 86.1,
      "targetPriceUsd": 86.1,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar exposicao a infraestrutura celular via satelite, uma das maiores optionalidades.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "NXE",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "NXE",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 9422.12,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 9.45,
      "currentPriceUsd": 9.45,
      "baseTradeValue": 9422.12,
      "targetPrice": 9.45,
      "targetPriceUsd": 9.45,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar posicao em ativo tier-1 de uranio, destacado como qualidade geologica superior.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "SMR",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "SMR",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7066.59,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 10.15,
      "currentPriceUsd": 10.15,
      "baseTradeValue": 7066.59,
      "targetPrice": 10.15,
      "targetPriceUsd": 10.15,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar exposicao a SMRs, tese nuclear com opcionalidade estrategica.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "ARR.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "ARR.AX",
      "role": "Opcionalidade",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.689465,
      "baseWeightPct": 2.0,
      "baseTargetValue": 4711.06,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 0.38,
      "currentPriceUsd": 0.2619967,
      "baseTradeValue": 4711.06,
      "targetPrice": 0.38,
      "targetPriceUsd": 0.2619967,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar rare earths geopolitico dos EUA em tamanho controlado pelo risco elevado.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "MP",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "MP",
      "role": "Opcionalidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 4711.06,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 54.28,
      "currentPriceUsd": 54.28,
      "baseTradeValue": 4711.06,
      "targetPrice": 54.28,
      "targetPriceUsd": 54.28,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar rare earths em producao nos EUA, com menor risco relativo que ARR.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "UUUU",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "UUUU",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 4711.06,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 14.22,
      "currentPriceUsd": 14.22,
      "baseTradeValue": 4711.06,
      "targetPrice": 14.22,
      "targetPriceUsd": 14.22,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar hibrido de uranio, monazita e rare earths para ampliar a cesta estrategica.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "SGML",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "SGML",
      "role": "Opcionalidade",
      "region": "Brazil",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 4711.06,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 12.41,
      "currentPriceUsd": 12.41,
      "baseTradeValue": 4711.06,
      "targetPrice": 12.41,
      "targetPriceUsd": 12.41,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar litio Brasil/ESG como opcionalidade de supply chain critica.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "QBTS",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "QBTS",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 4711.06,
      "currentValue": 11750.0,
      "currentValueLocal": 11750.0,
      "currentPrice": 23.5,
      "currentPriceUsd": 23.5,
      "baseTradeValue": -7038.94,
      "targetPrice": 28.2,
      "targetPriceUsd": 28.2,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "Reduzir quantum para tamanho de cesta, diminuindo risco de diluicao e volatilidade extrema.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "RGTI",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "RGTI",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.5,
      "baseTargetValue": 3533.29,
      "currentValue": 3736.0,
      "currentValueLocal": 3736.0,
      "currentPrice": 18.68,
      "currentPriceUsd": 18.68,
      "baseTradeValue": -202.71,
      "targetPrice": 22.42,
      "targetPriceUsd": 22.42,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "Manter opcionalidade em quantum, mas com peso menor e compativel com risco binario.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "LAES",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "LAES",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.5,
      "baseTargetValue": 3533.29,
      "currentValue": 3100.0,
      "currentValueLocal": 3100.0,
      "currentPrice": 3.1,
      "currentPriceUsd": 3.1,
      "baseTradeValue": 433.29,
      "targetPrice": 3.87,
      "targetPriceUsd": 3.87,
      "upsidePct": 25.0,
      "bias": "reduzir para cesta",
      "thesis": "Manter microcap de seguranca/semis apenas como componente pequeno da cesta.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "asset": "NAUFF",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "NAUFF",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.0,
      "baseTargetValue": 2355.53,
      "currentValue": 2980.0,
      "currentValueLocal": 2980.0,
      "currentPrice": 1.49,
      "currentPriceUsd": 1.49,
      "baseTradeValue": -624.47,
      "targetPrice": 1.86,
      "targetPriceUsd": 1.86,
      "upsidePct": 25.0,
      "bias": "manter pequeno",
      "thesis": "Reduzir para posicao pequena, mantendo opcionalidade no ciclo nuclear sem concentrar risco.",
      "fixed": false,
      "priceDate": "2026-07-01",
      "priceError": ""
    }
  ],
  "holdings": [
    {
      "symbol": "ICG",
      "name": "ICG",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 0.44,
      "currentPriceUsd": 0.31,
      "targetPrice": 0.44,
      "targetPriceUsd": 0.31,
      "upsidePct": 0.0,
      "bias": "manter apenas residual",
      "thesis": "posição residual CAD; baixa liquidez",
      "currentValueLocal": 3.52,
      "currentValue": 2.48,
      "modelTargetWeightPct": 0.0,
      "targetValue": 2.48,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-30",
      "priceError": ""
    },
    {
      "symbol": "AMZN",
      "name": "AMZN",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 241.7,
      "currentPriceUsd": 241.7,
      "targetPrice": 275.54,
      "targetPriceUsd": 275.54,
      "upsidePct": 14.0,
      "bias": "manter/aumentar moderado",
      "thesis": "cloud, ads e consumo; qualidade alta",
      "currentValueLocal": 12085.0,
      "currentValue": 12085.0,
      "modelTargetWeightPct": 5.0,
      "targetValue": 13777.000000000002,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "AMZN",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "COPX",
      "name": "COPX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 75.29,
      "currentPriceUsd": 75.29,
      "targetPrice": 84.32,
      "targetPriceUsd": 84.32,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "eletrificação e déficit estrutural de cobre",
      "currentValueLocal": 7529.0,
      "currentValue": 7529.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 8432.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "COPX",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "GOOGL",
      "name": "GOOGL",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 361.21,
      "currentPriceUsd": 361.21,
      "targetPrice": 404.56,
      "targetPriceUsd": 404.56,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "IA/search/cloud; valuation ainda razoável",
      "currentValueLocal": 9030.25,
      "currentValue": 9030.25,
      "modelTargetWeightPct": 5.0,
      "targetValue": 10114.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "GOOGL",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "HYMC",
      "name": "HYMC",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 23.07,
      "currentPriceUsd": 23.07,
      "targetPrice": 20.76,
      "targetPriceUsd": 20.76,
      "upsidePct": -10.0,
      "bias": "zerar ou residual",
      "thesis": "opcionalidade alta, execução fraca",
      "currentValueLocal": 230.7,
      "currentValue": 230.7,
      "modelTargetWeightPct": 0.0,
      "targetValue": 207.60000000000002,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "IBM",
      "name": "IBM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 286.25,
      "currentPriceUsd": 286.25,
      "targetPrice": 297.7,
      "targetPriceUsd": 297.7,
      "upsidePct": 4.0,
      "bias": "reduzir",
      "thesis": "defensiva, IA corporativa, menor convexidade",
      "currentValueLocal": 28625.0,
      "currentValue": 28625.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 29770.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "IBM",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "JPM",
      "name": "JPM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 334.07,
      "currentPriceUsd": 334.07,
      "targetPrice": 354.11,
      "targetPriceUsd": 354.11,
      "upsidePct": 6.0,
      "bias": "reduzir",
      "thesis": "banco de qualidade, mas peso atual alto",
      "currentValueLocal": 33407.0,
      "currentValue": 33407.0,
      "modelTargetWeightPct": 6.0,
      "targetValue": 35411.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "JPM",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "KTOS",
      "name": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 53.04,
      "currentPriceUsd": 53.04,
      "targetPrice": 62.59,
      "targetPriceUsd": 62.59,
      "upsidePct": 18.0,
      "bias": "manter",
      "thesis": "drones, sistemas autônomos e defesa",
      "currentValueLocal": 3182.4,
      "currentValue": 3182.4,
      "modelTargetWeightPct": 4.0,
      "targetValue": 3755.4,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "KTOS",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "LAES",
      "name": "LAES",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.1,
      "currentPriceUsd": 3.1,
      "targetPrice": 3.87,
      "targetPriceUsd": 3.87,
      "upsidePct": 25.0,
      "bias": "reduzir para cesta",
      "thesis": "microcap com opcionalidade e risco",
      "currentValueLocal": 3100.0,
      "currentValue": 3100.0,
      "modelTargetWeightPct": 1.5,
      "targetValue": 3870.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "LAES",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "MSFT",
      "name": "MSFT",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 384.28,
      "currentPriceUsd": 384.28,
      "targetPrice": 422.71,
      "targetPriceUsd": 422.71,
      "upsidePct": 10.0,
      "bias": "manter",
      "thesis": "cloud/IA; qualidade máxima",
      "currentValueLocal": 19214.0,
      "currentValue": 19214.0,
      "modelTargetWeightPct": 6.0,
      "targetValue": 21135.5,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "MSFT",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "NAUFF",
      "name": "NAUFF",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 1.49,
      "currentPriceUsd": 1.49,
      "targetPrice": 1.86,
      "targetPriceUsd": 1.86,
      "upsidePct": 25.0,
      "bias": "manter pequeno",
      "thesis": "opcionalidade em ciclo nuclear",
      "currentValueLocal": 2980.0,
      "currentValue": 2980.0,
      "modelTargetWeightPct": 1.0,
      "targetValue": 3720.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "NAUFF",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "NTDOY",
      "name": "NTDOY",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 10.75,
      "currentPriceUsd": 10.75,
      "targetPrice": 11.5,
      "targetPriceUsd": 11.5,
      "upsidePct": 7.0,
      "bias": "reduzir",
      "thesis": "qualidade, mas fora das teses anexas",
      "currentValueLocal": 806.25,
      "currentValue": 806.25,
      "modelTargetWeightPct": 0.0,
      "targetValue": 862.5,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "NVDA",
      "name": "NVDA",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 197.58,
      "currentPriceUsd": 197.58,
      "targetPrice": 217.34,
      "targetPriceUsd": 217.34,
      "upsidePct": 10.0,
      "bias": "reduzir peso",
      "thesis": "liderança em IA, valuation exige disciplina",
      "currentValueLocal": 39516.0,
      "currentValue": 39516.0,
      "modelTargetWeightPct": 8.0,
      "targetValue": 43468.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "NVDA",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "QBTS",
      "name": "QBTS",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 23.5,
      "currentPriceUsd": 23.5,
      "targetPrice": 28.2,
      "targetPriceUsd": 28.2,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "alto beta e risco de diluição",
      "currentValueLocal": 11750.0,
      "currentValue": 11750.0,
      "modelTargetWeightPct": 2.0,
      "targetValue": 14100.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "QBTS",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "RGTI",
      "name": "RGTI",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 18.68,
      "currentPriceUsd": 18.68,
      "targetPrice": 22.42,
      "targetPriceUsd": 22.42,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "alto beta e risco de diluição",
      "currentValueLocal": 3736.0,
      "currentValue": 3736.0,
      "modelTargetWeightPct": 1.5,
      "targetValue": 4484.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RGTI",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "RKLB",
      "name": "RKLB",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 100.07,
      "currentPriceUsd": 100.07,
      "targetPrice": 135.09,
      "targetPriceUsd": 135.09,
      "upsidePct": 35.0,
      "bias": "aumentar",
      "thesis": "uma das top 5 dos anexos; execução real",
      "currentValueLocal": 6004.2,
      "currentValue": 6004.2,
      "modelTargetWeightPct": 6.0,
      "targetValue": 8105.400000000001,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RKLB",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "RTX",
      "name": "RTX",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 191.78,
      "currentPriceUsd": 191.78,
      "targetPrice": 207.12,
      "targetPriceUsd": 207.12,
      "upsidePct": 8.0,
      "bias": "manter",
      "thesis": "defesa defensiva, menor upside que KTOS/RKLB",
      "currentValueLocal": 5753.4,
      "currentValue": 5753.4,
      "modelTargetWeightPct": 3.0,
      "targetValue": 6213.6,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RTX",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "SHLD",
      "name": "SHLD",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 61.2,
      "currentPriceUsd": 61.2,
      "targetPrice": 68.54,
      "targetPriceUsd": 68.54,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "defesa/segurança como tema estrutural",
      "currentValueLocal": 9180.0,
      "currentValue": 9180.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 10281.000000000002,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "SHLD",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "URA",
      "name": "URA",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 43.18,
      "currentPriceUsd": 43.18,
      "targetPrice": 49.66,
      "targetPriceUsd": 49.66,
      "upsidePct": 15.0,
      "bias": "manter",
      "thesis": "ciclo nuclear e demanda de energia para IA",
      "currentValueLocal": 4318.0,
      "currentValue": 4318.0,
      "modelTargetWeightPct": 5.0,
      "targetValue": 4966.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "URA",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "USGDF",
      "name": "USGDF",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.11,
      "currentPriceUsd": 0.11,
      "targetPrice": 0.11,
      "targetPriceUsd": 0.11,
      "upsidePct": 0.0,
      "bias": "zerar se possível",
      "thesis": "posição residual ilíquida",
      "currentValueLocal": 110.0,
      "currentValue": 110.0,
      "modelTargetWeightPct": 0.0,
      "targetValue": 110.0,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "XOVR",
      "name": "XOVR",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 21.11,
      "currentPriceUsd": 21.11,
      "targetPrice": 21.95,
      "targetPriceUsd": 21.95,
      "upsidePct": 4.0,
      "bias": "manter como caixa equivalente",
      "thesis": "equivalente defensivo/cash-like",
      "currentValueLocal": 2111.0,
      "currentValue": 2111.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 2195.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "XOVR",
      "priceDate": "2026-07-01",
      "priceError": ""
    }
  ],
  "residuals": [
    {
      "symbol": "ICG",
      "name": "ICG",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 0.44,
      "currentPriceUsd": 0.31,
      "targetPrice": 0.44,
      "targetPriceUsd": 0.31,
      "upsidePct": 0.0,
      "bias": "manter apenas residual",
      "thesis": "posição residual CAD; baixa liquidez",
      "currentValueLocal": 3.52,
      "currentValue": 2.48,
      "modelTargetWeightPct": 0.0,
      "targetValue": 2.48,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-30",
      "priceError": ""
    },
    {
      "symbol": "HYMC",
      "name": "HYMC",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 23.07,
      "currentPriceUsd": 23.07,
      "targetPrice": 20.76,
      "targetPriceUsd": 20.76,
      "upsidePct": -10.0,
      "bias": "zerar ou residual",
      "thesis": "opcionalidade alta, execução fraca",
      "currentValueLocal": 230.7,
      "currentValue": 230.7,
      "modelTargetWeightPct": 0.0,
      "targetValue": 207.60000000000002,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "NTDOY",
      "name": "NTDOY",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 10.75,
      "currentPriceUsd": 10.75,
      "targetPrice": 11.5,
      "targetPriceUsd": 11.5,
      "upsidePct": 7.0,
      "bias": "reduzir",
      "thesis": "qualidade, mas fora das teses anexas",
      "currentValueLocal": 806.25,
      "currentValue": 806.25,
      "modelTargetWeightPct": 0.0,
      "targetValue": 862.5,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    },
    {
      "symbol": "USGDF",
      "name": "USGDF",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.11,
      "currentPriceUsd": 0.11,
      "targetPrice": 0.11,
      "targetPriceUsd": 0.11,
      "upsidePct": 0.0,
      "bias": "zerar se possível",
      "thesis": "posição residual ilíquida",
      "currentValueLocal": 110.0,
      "currentValue": 110.0,
      "modelTargetWeightPct": 0.0,
      "targetValue": 110.0,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-07-01",
      "priceError": ""
    }
  ],
  "watchlist": [
    {
      "name": "American Rare Earths",
      "symbol": "ARR",
      "yahoo": "ARR.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.689465,
      "currentPrice": 0.38,
      "currentPriceUsd": 0.26,
      "targetPrice": 0.54,
      "targetPriceUsd": 0.37,
      "upsidePct": 45.0,
      "priority": "alta",
      "thesis": "top 5; terras raras EUA, geopolítica, muito risco",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "AST SpaceMobile",
      "symbol": "ASTS",
      "yahoo": "ASTS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Espaço",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 86.1,
      "currentPriceUsd": 86.1,
      "targetPrice": 120.54,
      "targetPriceUsd": 120.54,
      "upsidePct": 40.0,
      "priority": "alta",
      "thesis": "top 5; infraestrutura celular via satélite",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "NexGen Energy",
      "symbol": "NXE",
      "yahoo": "NXE",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 9.45,
      "currentPriceUsd": 9.45,
      "targetPrice": 12.28,
      "targetPriceUsd": 12.28,
      "upsidePct": 30.0,
      "priority": "alta",
      "thesis": "top 5; ativo tier-1 em urânio",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Rocket Lab",
      "symbol": "RKLB",
      "yahoo": "RKLB",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Espaço/defesa",
      "category": "Espaço/defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 100.07,
      "currentPriceUsd": 100.07,
      "targetPrice": 135.09,
      "targetPriceUsd": 135.09,
      "upsidePct": 35.0,
      "priority": "alta",
      "thesis": "top 5; execução operacional",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "NuScale Power",
      "symbol": "SMR",
      "yahoo": "SMR",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Nuclear SMR",
      "category": "Nuclear SMR",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 10.15,
      "currentPriceUsd": 10.15,
      "targetPrice": 13.19,
      "targetPriceUsd": 13.19,
      "upsidePct": 30.0,
      "priority": "alta",
      "thesis": "top 5; opcionalidade em SMRs",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "MP Materials",
      "symbol": "MP",
      "yahoo": "MP",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 54.28,
      "currentPriceUsd": 54.28,
      "targetPrice": 65.14,
      "targetPriceUsd": 65.14,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "produção de rare earths nos EUA; menor risco que ARR",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Lynas Rare Earths",
      "symbol": "LYC",
      "yahoo": "LYC.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.689465,
      "currentPrice": 18.09,
      "currentPriceUsd": 12.47,
      "targetPrice": 20.8,
      "targetPriceUsd": 14.34,
      "upsidePct": 15.0,
      "priority": "media",
      "thesis": "cadeia ex-China em escala",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Ucore Rare Metals",
      "symbol": "Ucore",
      "yahoo": "UURAF",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.39,
      "currentPriceUsd": 3.39,
      "targetPrice": 4.58,
      "targetPriceUsd": 4.58,
      "upsidePct": 35.0,
      "priority": "media",
      "thesis": "refino/separação, similar a ARR",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Aclara Resources",
      "symbol": "Aclara",
      "yahoo": "ARA.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 4.12,
      "currentPriceUsd": 2.9,
      "targetPrice": 5.36,
      "targetPriceUsd": 3.77,
      "upsidePct": 30.0,
      "priority": "media",
      "thesis": "heavy rare earths com narrativa ESG",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-30"
    },
    {
      "name": "Energy Fuels",
      "symbol": "UUUU",
      "yahoo": "UUUU",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Urânio/rare earths",
      "category": "Urânio/rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 14.22,
      "currentPriceUsd": 14.22,
      "targetPrice": 17.78,
      "targetPriceUsd": 17.78,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "urânio + monazita + rare earths",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Denison Mines",
      "symbol": "DNN",
      "yahoo": "DNN",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.08,
      "currentPriceUsd": 3.08,
      "targetPrice": 3.85,
      "targetPriceUsd": 3.85,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "ISR optionality no ciclo nuclear",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Global Atomic",
      "symbol": "GLO",
      "yahoo": "GLO.TO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 0.62,
      "currentPriceUsd": 0.44,
      "targetPrice": 0.81,
      "targetPriceUsd": 0.57,
      "upsidePct": 30.0,
      "priority": "baixa",
      "thesis": "alto leverage com risco Níger",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-30"
    },
    {
      "name": "Deep Yellow",
      "symbol": "DYL",
      "yahoo": "DYL.AX",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.689465,
      "currentPrice": 1.45,
      "currentPriceUsd": 1.0,
      "targetPrice": 1.74,
      "targetPriceUsd": 1.2,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "ciclo nuclear longo",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Fission Uranium",
      "symbol": "FCU",
      "yahoo": "FCU.TO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "Athabasca estratégico",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Ivanhoe Mines",
      "symbol": "IVN",
      "yahoo": "IVN.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 11.11,
      "currentPriceUsd": 7.81,
      "targetPrice": 13.11,
      "targetPriceUsd": 9.22,
      "upsidePct": 18.0,
      "priority": "media",
      "thesis": "opcionalidade global em cobre",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-30"
    },
    {
      "name": "Solaris Resources",
      "symbol": "SLS",
      "yahoo": "SLS.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 11.93,
      "currentPriceUsd": 8.39,
      "targetPrice": 14.91,
      "targetPriceUsd": 10.49,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "exploração de cobre; alto risco",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-30"
    },
    {
      "name": "Arizona Sonoran Copper",
      "symbol": "ASCU",
      "yahoo": "ASCU.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.703354,
      "currentPrice": 8.06,
      "currentPriceUsd": 5.67,
      "targetPrice": 9.67,
      "targetPriceUsd": 6.8,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "cobre doméstico americano",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-29"
    },
    {
      "name": "NGEx Minerals",
      "symbol": "NGEX",
      "yahoo": "NGEX.V",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 30.0,
      "priority": "baixa",
      "thesis": "altíssimo risco/recompensa",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Sigma Lithium",
      "symbol": "SGML",
      "yahoo": "SGML",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Brazil",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 12.41,
      "currentPriceUsd": 12.41,
      "targetPrice": 15.51,
      "targetPriceUsd": 15.51,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "Brasil + ESG + spodumene",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Patriot Battery Metals",
      "symbol": "PMET",
      "yahoo": "PMET.V",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "opcionalidade canadense",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Atlantic Lithium",
      "symbol": "ALL",
      "yahoo": "ALL.L",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "United Kingdom",
      "currency": "GBP",
      "currencyRaw": "GBp",
      "fxToUsd": 1.327986,
      "currentPrice": 0.16,
      "currentPriceUsd": 0.21,
      "targetPrice": 0.19,
      "targetPriceUsd": 0.25,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "Gana + opcionalidade africana",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-30"
    },
    {
      "name": "Lithium Argentina",
      "symbol": "LAAC",
      "yahoo": "LAAC",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Argentina",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 18.0,
      "priority": "baixa",
      "thesis": "ex-Lithium Americas Argentina",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Kratos",
      "symbol": "KTOS",
      "yahoo": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 53.04,
      "currentPriceUsd": 53.04,
      "targetPrice": 62.59,
      "targetPriceUsd": 62.59,
      "upsidePct": 18.0,
      "priority": "media",
      "thesis": "drones e sistemas autônomos",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Palantir",
      "symbol": "PLTR",
      "yahoo": "PLTR",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "IA/defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 125.73,
      "currentPriceUsd": 125.73,
      "targetPrice": 140.82,
      "targetPriceUsd": 140.82,
      "upsidePct": 12.0,
      "priority": "media",
      "thesis": "IA militar/inteligência; valuation alto",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Red Cat",
      "symbol": "RCAT",
      "yahoo": "RCAT",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Defesa drones",
      "category": "Defesa drones",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 10.55,
      "currentPriceUsd": 10.55,
      "targetPrice": 14.24,
      "targetPriceUsd": 14.24,
      "upsidePct": 35.0,
      "priority": "baixa",
      "thesis": "microcap em drones militares",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "BlackSky",
      "symbol": "BKSY",
      "yahoo": "BKSY",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Espaço",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 28.74,
      "currentPriceUsd": 28.74,
      "targetPrice": 35.92,
      "targetPriceUsd": 35.92,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "imagens em tempo real",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Planet Labs",
      "symbol": "PL",
      "yahoo": "PL",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Espaço/dados",
      "category": "Espaço/dados",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 31.61,
      "currentPriceUsd": 31.61,
      "targetPrice": 38.56,
      "targetPriceUsd": 38.56,
      "upsidePct": 22.0,
      "priority": "baixa",
      "thesis": "dados orbitais + IA",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Recursion",
      "symbol": "RXRX",
      "yahoo": "RXRX",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "AI biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.67,
      "currentPriceUsd": 3.67,
      "targetPrice": 4.59,
      "targetPriceUsd": 4.59,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "drug discovery + IA",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Beam Therapeutics",
      "symbol": "BEAM",
      "yahoo": "BEAM",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "Biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 33.48,
      "currentPriceUsd": 33.48,
      "targetPrice": 41.85,
      "targetPriceUsd": 41.85,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "base editing",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "CRISPR Therapeutics",
      "symbol": "CRSP",
      "yahoo": "CRSP",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "Biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 55.62,
      "currentPriceUsd": 55.62,
      "targetPrice": 66.74,
      "targetPriceUsd": 66.74,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "gene editing com opcionalidade",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Oklo",
      "symbol": "OKLO",
      "yahoo": "OKLO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "nuclear",
      "category": "Nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 52.45,
      "currentPriceUsd": 52.45,
      "targetPrice": 65.56,
      "targetPriceUsd": 65.56,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "microreatores + IA/energia",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Cadiz",
      "symbol": "CDZI",
      "yahoo": "CDZI",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "water",
      "category": "Água",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 4.08,
      "currentPriceUsd": 4.08,
      "targetPrice": 4.69,
      "targetPriceUsd": 4.69,
      "upsidePct": 15.0,
      "priority": "baixa",
      "thesis": "escassez hídrica",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Nutrien",
      "symbol": "NTR",
      "yahoo": "NTR",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "agriculture",
      "category": "Agricultura",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 63.57,
      "currentPriceUsd": 63.57,
      "targetPrice": 68.66,
      "targetPriceUsd": 68.66,
      "upsidePct": 8.0,
      "priority": "media",
      "thesis": "potássio/fertilizantes estratégicos",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    },
    {
      "name": "Mosaic",
      "symbol": "MOS",
      "yahoo": "MOS",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "agriculture",
      "category": "Agricultura",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 21.3,
      "currentPriceUsd": 21.3,
      "targetPrice": 23.0,
      "targetPriceUsd": 23.0,
      "upsidePct": 8.0,
      "priority": "media",
      "thesis": "segurança alimentar global",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-07-01"
    }
  ],
  "exports": {
    "marketPricesFile": "exports/market-prices.csv",
    "fxRatesFile": "exports/fx-rates.csv",
    "scenarioSummaryFile": "exports/scenario-summary.csv",
    "scenarioFiles": [
      {
        "id": "study",
        "label": "Base do estudo",
        "file": "scenario-study.csv"
      },
      {
        "id": "defensive",
        "label": "Defensivo global",
        "file": "scenario-defensive.csv"
      },
      {
        "id": "convex",
        "label": "Convexidade",
        "file": "scenario-convex.csv"
      }
    ],
    "publicDataFile": "public/data.js"
  }
};
